name: heroin
channels:
  - conda-forge
  - r
  - defaults
dependencies:
  - python>=3.9
  - jupyter
  - jupyter-book
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - plotly
  - scipy
  - openjdk
  - lxml
  - r-base>=4.1
  - r-essentials
  - r-tidyverse
  - r-gridExtra
  - r-moments
  - pip
  - pip:
    - sodapy
    - zipfile-deflate64
    - tabula-py
    - rpy2