name: heroin
channels:
  - conda-forge
  - r
  - defaults
dependencies:
  - python
  - jupyter
  - numpy
  - pandas
  - seaborn
  - matplotlib
  - plotly
  - scipy
  - openjdk
  - lxml
  - pip
  - pip:
    - sodapy
    - zipfile-deflate64
    - tabula-py
    - rpy2